// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfSwMnXXLZtCRdyp-nlBkPoz1QNek5cJ8',
    appId: '1:130270115060:web:bac47772b2ffe4f0601aa1',
    messagingSenderId: '130270115060',
    projectId: 'citizen-mobile-app-284a2',
    authDomain: 'citizen-mobile-app-284a2.firebaseapp.com',
    storageBucket: 'citizen-mobile-app-284a2.firebasestorage.app',
    measurementId: 'G-GG804D8FKC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARHyCccqo0rlA3hHOijcUJ8gixdBlXXu4',
    appId: '1:130270115060:android:4450fccc81656e03601aa1',
    messagingSenderId: '130270115060',
    projectId: 'citizen-mobile-app-284a2',
    storageBucket: 'citizen-mobile-app-284a2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh6DcguzQuNMPB_LqMm1v3qBRyhBm5b54',
    appId: '1:130270115060:ios:09be9ba3b95d27d7601aa1',
    messagingSenderId: '130270115060',
    projectId: 'citizen-mobile-app-284a2',
    storageBucket: 'citizen-mobile-app-284a2.firebasestorage.app',
    iosBundleId: 'com.example.citizenMobileApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh6DcguzQuNMPB_LqMm1v3qBRyhBm5b54',
    appId: '1:130270115060:ios:09be9ba3b95d27d7601aa1',
    messagingSenderId: '130270115060',
    projectId: 'citizen-mobile-app-284a2',
    storageBucket: 'citizen-mobile-app-284a2.firebasestorage.app',
    iosBundleId: 'com.example.citizenMobileApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfSwMnXXLZtCRdyp-nlBkPoz1QNek5cJ8',
    appId: '1:130270115060:web:c750233234ecc462601aa1',
    messagingSenderId: '130270115060',
    projectId: 'citizen-mobile-app-284a2',
    authDomain: 'citizen-mobile-app-284a2.firebaseapp.com',
    storageBucket: 'citizen-mobile-app-284a2.firebasestorage.app',
    measurementId: 'G-NX8MDK00SS',
  );
}
