const List<String> taclobanBarangays = [
  'Barangay 1 (Libertad)',
  'Barangay 2 (Jones)',
  'Barangay 3 (Upper Nulatula)',
  'Barangay 4 (Libertad)',
  'Barangay 5 (T. Claudio)',
  'Barangay 5-A (T. Claudio)',
  'Barangay 6',
  'Barangay 6-A (Sto. Nino)',
  'Barangay 7',
  'Barangay 8 (T. Claudio)',
  'Barangay 8-A',
  'Barangay 12 (GE Palanog)',
  'Barangay 13 (Salazar/J. Romualdez)',
  'Barangay 14',
  'Barangay 15',
  'Barangay 16',
  'Barangay 17',
  'Barangay 18',
  'Barangay 19',
  'Barangay 20',
  'Barangay 21 (P. Burgos)',
  'Barangay 22',
  'Barangay 23',
  'Barangay 23-A',
  'Barangay 24',
  'Barangay 25',
  'Barangay 26 (P. Gomez)',
  'Barangay 27',
  'Barangay 28',
  'Barangay 29 (P. Gomez)',
  'Barangay 30 (Burgos)',
  'Barangay 31',
  'Barangay 32',
  'Barangay 33',
  'Barangay 34 (Real)',
  'Barangay 35',
  'Barangay 35-A',
  'Barangay 36 (Sabang)',
  'Barangay 36-A (Sabang)',
  'Barangay 37 (Sea Wall)',
  'Barangay 37-A (G.E. Palanog Gawad Kalinga Village)',
  'Barangay 38 (Calvary Hill)',
  'Barangay 39 (Calvary Hill)',
  'Barangay 40 (Calvary Hill)',
  'Barangay 41 (Calvary Hill)',
  'Barangay 42',
  'Barangay 42-A (Quarry)',
  'Barangay 42-B (Quarry)',
  'Barangay 43',
  'Barangay 43-A (Quarry)',
  'Barangay 43-B (Quarry)',
  'Barangay 44',
  'Barangay 44-A (Quarry)',
  'Barangay 44-B (Quarry)',
  'Barangay 45',
  'Barangay 46 (Imelda/Juan Luna)',
  'Barangay 47',
  'Barangay 48',
  'Barangay 48-A',
  'Barangay 48-B',
  'Barangay 49 (Youngfield)',
  'Barangay 50 (Youngfield)',
  'Barangay 50-A (Youngfield)',
  'Barangay 50-B (Youngfield)',
  'Barangay 51',
  'Barangay 51-A',
  'Barangay 52 (Lucban Magallanes)',
  'Barangay 53 (Magallanes)',
  'Barangay 54 (Magallanes)',
  'Barangay 54-A (Magallanes)',
  'Barangay 55 (El Reposo)',
  'Barangay 56 (El Reposo)',
  'Barangay 56-A (El Reposo)',
  'Barangay 57 (Whitelane Sampaguita)',
  'Barangay 58',
  'Barangay 59 (Sagkahan Picas)',
  'Barangay 59-A (Sampaguita)',
  'Barangay 59-B (Sampaguita)',
  'Barangay 59-E (Sagkahan Picas)',
  'Barangay 60 (Sagkahan Aslum)',
  'Barangay 60-A (Sagkahan)',
  'Barangay 61 (Sagkahan)',
  'Barangay 62 (Sagkahan Saging)',
  'Barangay 62-A (Sagkahan Ilong)',
  'Barangay 62-B (Sagkahan Picas)',
  'Barangay 63 (Sagkahan Mangga)',
  'Barangay 64 (Sagkahan Bliss)',
  'Barangay 65 (Paseo de Legaspi)',
  'Barangay 66 (Anibong)',
  'Barangay 66-A (Anibong)',
  'Barangay 67 (Anibong)',
  'Barangay 68 (Anibong)',
  'Barangay 69 (Anibong, Happy Land)',
  'Barangay 70 (Anibong, Rawis)',
  'Barangay 71 (Naga-naga)',
  'Barangay 72 (PHHC Seaside)',
  'Barangay 73 (PHHC Mountainside)',
  'Barangay 74 (Lower Nula-Tula)',
  'Barangay 75 (Fatima Village)',
  'Barangay 76 (Fatima Village)',
  'Barangay 77 (Fatima Village)',
  'Barangay 78 (Marasbaras)',
  'Barangay 79 (Marasbaras)',
  'Barangay 80 (Marasbaras)',
  'Barangay 81 (Marasbaras)',
  'Barangay 82 (Marasbaras)',
  'Barangay 83 (Paraiso)',
  'Barangay 83-A (Burayan)',
  'Barangay 83-B (San Jose, Cogon)',
  'Barangay 83-C (San Jose)',
  'Barangay 84 (San Jose)',
  'Barangay 85 (San Jose)',
  'Barangay 86 (San Jose)',
  'Barangay 87 (San Jose)',
  'Barangay 88 (San Jose)',
  'Barangay 89 (San Jose, Baybay)',
  'Barangay 90 (San Jose)',
  'Barangay 91 (Abucay)',
  'Barangay 92 (Apitong)',
  'Barangay 93 (Bagacay)',
  'Barangay 94 (Tigbao)',
  'Barangay 94-A (Basper)',
  'Barangay 95 (Caibaan)',
  'Barangay 95-A (Caibaan)',
  'Barangay 96 (Calanipawan)',
  'Barangay 97 (Cabalawan)',
  'Barangay 98 (Camansihay)',
  'Barangay 99 (Diit)',
  'Barangay 100 (San Roque)',
  'Barangay 101 (New Kawayan)',
  'Barangay 102 (Kawayan)',
  'Barangay 103 (Palanog)',
  'Barangay 103-A (San Paglaum)',
  'Barangay 104 (Salvacion)',
  'Barangay 105 (Suhi)',
  'Barangay 106 (Santo Nino)',
  'Barangay 107 (Santa Elena)',
  'Barangay 108 (Tagapuro)',
  'Barangay 109 (V&G Subdivision)',
  'Barangay 109-A (V&G Subdivision)',
  'Barangay 110 (Utap)',
];
